openapi: '3.0.1'
info:
  title: nuu-playground-api
  description: 勉強用
  version: '1.0.0'
servers:
  - url: 'http://localhost:88/api'
    description: 開発環境
paths:
  /test:
    get:
      description: 'レスポンス確認'
      responses:
        '200':
          description: '成功'
        '500':
          description: 'エラー'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/refresh_token_cognito'
components:
  schemas:
    error:
      type: 'object'
      properties:
        message:
          type: 'string'
          example: 'error'
  x-amazon-apigateway-integrations:
    refresh_token_cognito:
      uri: '${arn_hello_world}'
      payloadFormatVersion: '2.0'
      type: 'aws_proxy'
      httpMethod: 'POST'
      credentials: '${arn_invoke_role}'
      connectionType: 'INTERNET'
